version '3.7'
services:
  sample:
    container_name: kubelauncer
    build:
      context:
      dockerfile: dockerfile
  
    volumes:
      -'.:/app'
      -'app/node_modules'
    ports:
      -3001:3000
    -enviroment: